# Generated by Django 5.0.4 on 2024-07-28 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_foodcriticrestaurantreview_regularrestaurantreview_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcriticrestaurantreview',
            options={'ordering': ['-rating'], 'verbose_name': 'Food Critic Review', 'verbose_name_plural': 'Food Critic Reviews'},
        ),
    ]
