# Generated by Django 5.0.4 on 2024-07-04 21:42

from django.db import migrations


def create_age_group_info(apps, schema_editor):
    person_model = apps.get_model('main_app', 'Person')
    for person in person_model.objects.all():
        if person.age <= 12:
            person.age_group = 'Child'
        elif 13 <= person.age <= 17:
            person.age_group = 'Teen'
        elif person.age >= 18:
            person.age_group = 'Adult'
        person_model.save()


def reverse_create_age_group_info(apps, schema_editor):
    person_model = apps.get_model('main_app', 'Person')
    for person in person_model.objects.all():
        person.age_group = 'No age group'
        person_model.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_person'),
    ]

    operations = [
        migrations.RunPython(create_age_group_info, reverse_code=reverse_create_age_group_info)
    ]
