# Generated by Django 5.0.4 on 2024-07-04 22:41

from django.db import migrations


def generate_new_price(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    for smartphone in smartphone_model.objects.all():
        new_price = len(smartphone.brand) * 120
        smartphone.price = new_price
        smartphone.save()


def reverse_generate_new_price(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    for smartphone in smartphone_model.objects.all():
        old_price = len(smartphone.brand) / 120
        smartphone.price = old_price
        smartphone.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [
        migrations.RunPython(generate_new_price, reverse_code=reverse_generate_new_price)
    ]
