# Generated by Django 5.0.4 on 2024-07-04 22:54

from django.db import migrations


def generate_new_category(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    for smartphone in smartphone_model.objects.all():
        if smartphone.price >= 750:
            smartphone.category = 'Expensive'
        else:
            smartphone.category = 'Cheap'
        smartphone.save()


def reverse_generate_new_category(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    for smartphone in smartphone_model.objects.all():
        smartphone.category = smartphone._meta.get_field('category').default
        smartphone.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_category_mofiy'),
    ]

    operations = [
        migrations.RunPython(generate_new_category, reverse_code=reverse_generate_new_category)
    ]
